version: '2'

services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

  mongodb:
  mongodb:
    image: aashreys/mongo-auth:latest
    environment:
      # provide your credentials here
      - AUTH=yes
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=further&further
      - MONGODB_APPLICATION_DATABASE=colmena
      - MONGODB_APPLICATION_USER=wushuu
      - MONGODB_APPLICATION_PASS=woyoadmin
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/configdb
      - mongo:/data/db

volumes:
  mongo:
    driver: local
